In [68]:
import numpy as np
from typing import List
import random


In [142]:
# yuval points means that points have error values
class YPoint:
    def __init__(self, x,y,err) -> None:
        self.x = x
        self.y = y 
        self.err = err


class Param:
    def __init__(self, min, max, n= 31) -> None: #n should be odd
        self.min = min
        self.max = max
        self.n = n
    
    def range(self):
        return np.linspace(self.min,self.max,num=self.n)
    
    def get_new_range(self, value):
        width = (self.max-self.min) / (self.n-1)
        #print (self, " | " ,value, " | ",  Param(max(value - width, self.min), min(value+width, self.max)))
        return Param(max(value - width, self.min), min(value+width, self.max))
        #return Param(value - width, value+width)
    
    def __str__(self):
        return f"min: {self.min}, max: {self.max}"




In [143]:
def do_func(params, x):
    return params[0] +params[1]*x 

def find_chi(params: List[float], ypoints: List[YPoint]) -> int:
    return sum([((do_func(params, ypoint.x) - ypoint.y)/(ypoint.err))**2 for ypoint in ypoints])

def min_chi_on_params(ypoints: List[YPoint], params: List[Param]):
    n_params = []
    min_chi = float('inf')
    min_param_comb= []
    params_combinations = np.array(np.meshgrid(*list(map(lambda param: param.range(), params)))).T.reshape(-1,len(params))
    for params_combination in params_combinations:
        res = find_chi(params_combination, ypoints)
        if res < min_chi:
            min_chi = res
            min_param_comb=params_combination
            n_params =[]
            for i in range(len(params_combination)):
                n_params.append(params[i].get_new_range(params_combination[i]))
    return n_params, min_chi , min_param_comb

def find_chi_repete_params(ypoints: List[YPoint], params: List[Param], res_chi = 0.00000001):
    min_chi = float('inf')
    n_min_chi = 100000000000000000000000000
    counter = 0
    n_params, n_min_chi, min_param_comb = min_chi_on_params(ypoints, params)
    thepupik = " ".join(str(s) for s in n_params)
    print(f"{counter} \n old chi: {min_chi} | new chi: {n_min_chi} | min_comb: {min_param_comb}\n param: {thepupik} \n")

    while (min_chi - n_min_chi) > res_chi:

        min_chi = n_min_chi
        counter +=1

        n_params, n_min_chi, min_param_comb = min_chi_on_params(ypoints, n_params)
        thepupik = " ".join(str(s) for s in n_params)
        print(f"{counter} \n old chi: {min_chi} | new chi: {n_min_chi} | min_comb: {min_param_comb}\n param: {thepupik} \n")
    return n_min_chi, min_param_comb



In [144]:
# inputs 
ypoints = [
    YPoint(1,3,0.1),
    YPoint(2,5,0.1),
    YPoint(3,7,0.1),
    YPoint(4,9,0.1),
    YPoint(5,11,0.1),
    YPoint(6,13,0.1),
    YPoint(7,15,0.1),
    YPoint(8,17,0.1),
    YPoint(9,19,0.1),
    YPoint(4,9,0.1),
    YPoint(5,11,0.1),
    YPoint(6,13,0.1),
    YPoint(7,15,0.1),
    YPoint(8,17,0.1),
    YPoint(9,19,0.1),
    YPoint(10,21,0.1),
    YPoint(11,23,0.1),
    YPoint(12,25,0.1),
    YPoint(13,27,0.1),
    YPoint(14,29,0.1),
    YPoint(15,31,0.1)
]
params: List[Param] = [Param(-20,11), Param(-5,9)]


In [145]:
N=10
chi_list=[]
a_s_list=[]
for i in range(N):
    random_ypoints=random.choices(ypoints,k=len(ypoints))
    chi, a_s = find_chi_repete_params(random_ypoints, params)
    chi_list.append(chi)
    a_s_list.append(a_s)

0 
 old chi: inf | new chi: 233.33333333333164 | min_comb: [0.66666667 2.        ]
 param: min: -0.3666666666666656, max: 1.7000000000000013 min: 1.5333333333333332, max: 2.466666666666667 

1 
 old chi: 233.33333333333164 | new chi: 0.2592592592593403 | min_comb: [1.01111111 2.        ]
 param: min: 0.9422222222222235, max: 1.0800000000000014 min: 1.968888888888889, max: 2.031111111111111 

2 
 old chi: 0.2592592592593403 | new chi: 0.007789300411537795 | min_comb: [1.00192593 2.        ]
 param: min: 0.9973333333333346, max: 1.00651851851852 min: 1.9979259259259259, max: 2.002074074074074 

3 
 old chi: 0.007789300411537795 | new chi: 1.6592592592841578e-05 | min_comb: [1.00008889 2.        ]
 param: min: 0.999782716049384, max: 1.0003950617283963 min: 1.9998617283950617, max: 2.0001382716049383 

4 
 old chi: 1.6592592592841578e-05 | new chi: 1.1016206881750166e-07 | min_comb: [1.00000724 2.        ]
 param: min: 0.9999868312757213, max: 1.0000276543209887 min: 1.999990781893004, ma

In [146]:
chi_list

[4.4959518123201737e-13,
 4.4959517993244226e-13,
 4.4959518123201737e-13,
 4.4959518123201737e-13,
 4.4959517993244226e-13,
 4.4959517993244226e-13,
 4.4959517993244226e-13,
 4.4959518123201737e-13,
 4.4959518123201737e-13,
 4.4959518123201737e-13]

In [147]:
a_s_list

[array([0.99999999, 2.        ]),
 array([0.99999999, 2.        ]),
 array([0.99999999, 2.        ]),
 array([0.99999999, 2.        ]),
 array([0.99999999, 2.        ]),
 array([0.99999999, 2.        ]),
 array([0.99999999, 2.        ]),
 array([0.99999999, 2.        ]),
 array([0.99999999, 2.        ]),
 array([0.99999999, 2.        ])]